// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JyBqynWvKOzXAGXIGpFiptkAwMOq6FI',
    appId: '1:672798585473:web:da5ee39d84c8607bcd5380',
    messagingSenderId: '672798585473',
    projectId: 'food-delivery-app-626aa',
    authDomain: 'food-delivery-app-626aa.firebaseapp.com',
    storageBucket: 'food-delivery-app-626aa.firebasestorage.app',
    measurementId: 'G-J06ZZXHYRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpl_QxsQm1-z3OIfCkGrJJymXBS5K5DFY',
    appId: '1:672798585473:android:689b771a9f4535fecd5380',
    messagingSenderId: '672798585473',
    projectId: 'food-delivery-app-626aa',
    storageBucket: 'food-delivery-app-626aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf7n6SWPTK6Z7cIFbR0UkJOb964ILKNWU',
    appId: '1:672798585473:ios:884fec0a0a33a549cd5380',
    messagingSenderId: '672798585473',
    projectId: 'food-delivery-app-626aa',
    storageBucket: 'food-delivery-app-626aa.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf7n6SWPTK6Z7cIFbR0UkJOb964ILKNWU',
    appId: '1:672798585473:ios:884fec0a0a33a549cd5380',
    messagingSenderId: '672798585473',
    projectId: 'food-delivery-app-626aa',
    storageBucket: 'food-delivery-app-626aa.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JyBqynWvKOzXAGXIGpFiptkAwMOq6FI',
    appId: '1:672798585473:web:770eed55fbcd6a30cd5380',
    messagingSenderId: '672798585473',
    projectId: 'food-delivery-app-626aa',
    authDomain: 'food-delivery-app-626aa.firebaseapp.com',
    storageBucket: 'food-delivery-app-626aa.firebasestorage.app',
    measurementId: 'G-FJFMC7G4RD',
  );
}
